### ISSUE TITLE
Rename as-installed library name in line with repo rename

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-twincat-common-components#59]
## Current Behavior

The as-installed library name is lcls2-cc-lib

## Expected Behavior

In line with the rename of this repository to lcls-twincat-common-components, the as-installed library names should be updated to match.
It is not necessary to re-release older versions of the library with the new name, but it would be nice if there was a way to link them on the twincat side.

## Context / environment

Reduce confusion in the future by having the same name for the repository as in twincat

## Suggested Solution

Short PR to change the name, or include it on the next update to this repo

**Comment by klauer** [comment]
Repository name has been changed. README was tweaked for new docs URL.

New name is: `lcls-twincat-common-components`
